### ISSUE TITLE
Hello message should contains all public keys

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#547]
## Description

Currently, the hello message only contains one public key (or consensus key). If a node has more than one consensus key, it broadcasts one hello message per key.

### How To Reproduce

We should revise the hello message to include all the consensus keys. To sign the message, we could aggregate all the keys and sign the message using the aggregated key.

~~This change needs to be **backward** compatible in Testnet.~~
~~We have two choices:~~
~~1. Define a new hello message (v2)~~
~~2. Modify the current hello message to support both versions~~

### What Happened

We receive multiple hello messages when a node joins the network.

### Expected Behavior

We should receive only one message per node.

**Comment by RiXelanya** [comment]
Hello. I would like to contribute to this. But I still dont know how to aggregate the public key? As for signature I understand we can use the bls.aggregate function defined in crypto folder but I dont know how to aggregate the public key

**Comment by b00f** [comment]
Some ideas:

1- We should add a new function for aggregating public keys, [here](https://github.com/pactus-project/pactus/blob/2167ca92c9f0742a6561d337da5e5c110177be1a/crypto/bls/bls.go#L11C2-L11C2)

The public key is a G2 point on the BLS curve, so to aggregate public keys we can simply add them together. Make sure you write good test.  

2- Hello message should be modified to be backward compatible:

```go
type HelloMessage struct {
	PeerID      peer.ID        `cbor:"1,keyasint"`
	Agent       string         `cbor:"2,keyasint"`
	Moniker     string         `cbor:"3,keyasint"`
	PublicKey   *bls.PublicKey         `cbor:"4,keyasint,omitempty"`
	PublicKeys   []*bls.PublicKey      `cbor:"9,keyasint,omitempty"`
	Signature   *bls.Signature `cbor:"5,keyasint"`
	Height      uint32         `cbor:"6,keyasint"`
	Flags       int            `cbor:"7,keyasint"`
	GenesisHash hash.Hash      `cbor:"8,keyasint"`

}
```

3- 

- If user runs old version:
It broadcasts 32 Hello messages, we know it is old because the `PublicKeys` is nil. 

- If user runs new version:
 It should broadcast 32 Hello messages with corresponding `PublicKey` (to maintain backward compatibility)
 and one Hello message, with PublicKey is nil, but the `PublicKeys` field should be filled with 32 keys and one aggregated signature.
 
4- Question:
Should we be worried about invalid public keys, such as the infinite point, in this case? 
I don't see any issues here, but it's a good idea to include this check. Perhaps we should modify the Public Key interface to add an `IsValid` API. Let's do this in a separate pull request (PR).

**Comment by amirvalhalla** [comment]
@RiXelanya 

do you still wanna solve this issue or not ? because I want to solve this issue and if you give up or etc... please tell me to solve this issue.

**Comment by b00f** [comment]
Item 1 is fixed on #576

**Comment by RiXelanya** [comment]
> @RiXelanya
> 
> do you still wanna solve this issue or not ? because I want to solve this issue and if you give up or etc... please tell me to solve this issue.

I am still working on it

**Comment by RiXelanya** [comment]
I tried to do it but the code caused test failure. I have looked at the failing test code and still dont understand how exactly does my addition cause the failure. @amirvalhalla @b00f

**Comment by amirvalhalla** [comment]
@RiXelanya 
I've checked your pull request, for the first step please fix my comment that I've put it to [your pull request](https://github.com/pactus-project/pactus/pull/579), meanwhile you're fixing my comment I'll check the cause of your failure.

**Comment by RiXelanya** [comment]
I am sorry. Some personal stuff happened. I have to give up. @amirvalhalla @b00f
